version: '3.8'
name: iris
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: sh -c "python3 initial_data.py && uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - "./app:/app"
    ports:
      - "80:80"
    env_file:
      - example.env
    depends_on:
      - database
    restart: on-failure:5

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - example.env
