name: iris-prod
services:
  api:
    image: ghcr.io/hendrik127/iris_api:main
    command: sh -c "python3 initial_data.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - example.env
    depends_on:
      - database
    restart: on-failure:5

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - example.env
